#!/bin/sh

set -e

appDir=${DEPLOY_DIR:-/deployments}
echo "Checking *.war in $appDir"
if [ -d ${appDir} ]; then
  target="${CATALINA_HOME}/webapps"
  for i in ${appDir}/*.war; do
     file=$(basename ${i})
     echo "Linking $i --> $target"
     if [ -f "${target}/${file}" ]; then
         rm "${target}/${file}"
     fi
     dir=$(basename ${i} .war)
     if [ x${dir} != x ] && [ -d "${target}/${dir}" ]; then
         rm -r "$target/${dir}"
     fi
     ln -s ${i} "${target}/${file}"
  done
fi

export JPDA_ADDRESS="localhost:${JAVA_DEBUG_PORT:-5005}"
if ! echo "${JAVA_DEBUG_SUSPEND:-n}" | grep -q -e '^\(false\|n\|no\|0\)$'; then
  export JPDA_SUSPEND="y"
fi

if [ "${JAVA_ENABLE_DEBUG:-false}" = "true" ]; then
  echo "Running catalina in debug mode ($JPDA_ADDRESS)"
  exec catalina.sh jpda run
else
  echo "Running catalina normal mode"
  exec catalina.sh run
fi
