#!/bin/sh
# ==============================================================================
# Configure JVM options for Prometheus Agent
#
# Usage: JAVA_OPTS="$JAVA_OPTS $(source ${JBOSS_CONTAINER_PROMETHEUS_MODULE}/prometheus-opts && get_prometheus_opts)"
#
# Env Vars respected:
#
# AB_PROMETHEUS_OFF: Disables the use of Prometheus Java Agent.
#
# AB_PROMETHEUS_PORT: Port to use for the Prometheus JMX Exporter.
#   Defaults to 9779.
#
# AB_PROMETHEUS_JMX_EXPORTER_CONFIG: Path to configuration to use for the
#   Prometheus JMX Exporter.  Defaults to:
#   /opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
#

source "$JBOSS_CONTAINER_UTIL_LOGGING_MODULE/logging.sh"

# echo's a complete -javaagent option based on the above variables.
function get_prometheus_opts() {
    if ! echo "${AB_PROMETHEUS_OFF:-false}" | grep -q -e '^\(true\|y\|yes\|1\)$'; then
        echo "-javaagent:/usr/share/java/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=${AB_PROMETHEUS_PORT:-9779}:${AB_PROMETHEUS_JMX_EXPORTER_CONFIG:-/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml}"
    fi
    echo ""
}