name: Build Images

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  TAG: latest

jobs:
  build-images:
    name: ${{ matrix.image.name }} (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
        image:
          - name: 'jkube-java'
            args: ''
          - name: 'jkube-java-25'
            args: ''
          - name: 'jkube-java-21'
            args: ''
          - name: 'jkube-java-17'
            args: ''
          - name: 'jkube-java-11'
            args: ''
          - name: 'jkube-jetty9'
            args: ''
          - name: 'jkube-karaf'
            args: ''
          - name: 'jkube-remote-dev'
            args: ''
          - name: 'jkube-tomcat9'
            args: --no-squash
          - name: 'jkube-tomcat'
            args: --no-squash
        exclude:
          - runner: ubuntu-24.04-arm
            image:
              name: 'jkube-jetty9'
              args: ''
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Install CEKit
        uses: cekit/actions-setup-cekit@v1.1.7
      - name: Compute arch
        run: |
          echo "ARCH=$(docker version --format '{{.Server.Arch}}')" >> $GITHUB_ENV
      - name: Build ${{ matrix.image.name }}
        run: |
          echo "Building quay.io/jkube/${{ matrix.image.name }}:${TAG}"
          cekit --descriptor ${{ matrix.image.name }}.yaml build docker ${{ matrix.image.args }} --tag="quay.io/jkube/${{ matrix.image.name }}:${TAG}"
      - name: Test
        if: success()
        run: |
          ./scripts/test-${{ matrix.image.name }}.sh
      - name: Trivy vulnerability report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db'
        with:
          image-ref: 'quay.io/jkube/${{ matrix.image.name }}:${{ env.TAG }}'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '0'
          format: 'json'
          output: '${{ matrix.image.name }}-${{ env.ARCH }}.trivy-report.json'
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'quay.io/jkube/${{ matrix.image.name }}:${{ env.TAG }}'
          format: 'cyclonedx'
          output: '${{ matrix.image.name }}-${{ env.ARCH }}.sbom.json'
      - name: Upload Trivy report and SBOM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: security-${{ matrix.image.name }}-${{ env.ARCH }}
          path: |
            ${{ matrix.image.name }}-${{ env.ARCH }}.trivy-report.json
            ${{ matrix.image.name }}-${{ env.ARCH }}.sbom.json
